import React from "react";
import Head from "next/head";
import { Box, Typography } from "@mui/material";

import GameLayout from "@/layouts/Game";
import Infos from "@/components/game/Infos";
import { GameContext } from "@/context/GameContext";
import { useUser } from "@clerk/nextjs";
import Player from "@/components/game/Player";
import Board from "@/components/game/Board";
import GameState from "@/components/game/GameState";

export default function Game() {
  const { game } = React.useContext(GameContext);
  const { user } = useUser();

  if (!game || !user)
    return (
      <GameLayout>
        <Typography variant="h1">Game loading...</Typography>
      </GameLayout>
    );

  const me = game.player1 === user.id ? "player1" : "player2";
  const opponent = me === "player1" ? "player2" : "player1";

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GameLayout>
        <Infos />
        <Box sx={styles.root}>
          <Board player={opponent} />
          <GameState />
          <Board player={me} />
        </Box>
      </GameLayout>
    </>
  );
}

const styles = {
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    gap: 4,
  },
};
