import React from "react";
import Head from "next/head";
import { Typography } from "@mui/material";

import Game from "@/layouts/Game";

const game = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Game>
        <Typography>Home</Typography>
      </Game>
    </>
  );
};

export default game;
